version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vw
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
    volumes:
      - vw-data:/data/

  reverse_proxy:
    image: nginx:latest
    container_name: rp
    restart: unless-stopped
    environment:
      HOST_FQDN: "${HOST_FQDN}"
    volumes:
      - .docker/reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/reverse_proxy/default.conf.template:/etc/nginx/templates/variables.conf.template
      - .docker/pki/cert.pem:/etc/ssl/certs/cert.pem:ro
      - .docker/pki/cert.key:/etc/ssl/private/cert.key:ro

    ports:
      - 8080:80
      - 8443:443

volumes:
  vw-data:
