version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vw
    environment: 
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
    volumes:
      - vw-data:/data/

  reverse_proxy:
    image: nginx:latest
    container_name: rp
    volumes:
      - .docker/reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/pki/cert.pem:/etc/ssl/certs/cert.pem
      - .docker/pki/cert.key:/etc/ssl/private/cert.key

    ports:
      - 8080:80
      - 8443:443

volumes:
  vw-data:
